// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKp8LBYBMhwrQYVmtsZQzFnbphmGgW28',
    appId: '1:496207937067:web:46816d94b6883ecaaff46e',
    messagingSenderId: '496207937067',
    projectId: 'uas-21312073-c4361',
    authDomain: 'uas-21312073-c4361.firebaseapp.com',
    storageBucket: 'uas-21312073-c4361.appspot.com',
    measurementId: 'G-BGVQL66G7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiPjTdNC8hqPjerNzOgkQG4T23G4Q0tJ0',
    appId: '1:496207937067:android:76b64b5651f27b6eaff46e',
    messagingSenderId: '496207937067',
    projectId: 'uas-21312073-c4361',
    storageBucket: 'uas-21312073-c4361.appspot.com',
  );
}
